all:
  vars:
    control_plane_endpoint: 192.168.86.48
    load_balancer_ip_pool:
      - 192.168.86.224/27
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.86.48, mac: '1c:69:7a:0a:bb:c4', disk: sda, network_interface: eth0}
        metal1: {ansible_host: 192.168.86.71, mac: '1c:69:7a:0a:95:1e', disk: sda, network_interface: eth0}
        metal2: {ansible_host: 192.168.86.66, mac: '1c:69:7a:0a:1f:c2', disk: sda, network_interface: eth0}
    workers:
      hosts: {}
