plausible-analytics:
  baseURL: https://plausible.192.168.86.224.nip.io
  secretKeyBase: "FqdHvCieEUPSWijlNvYfd8zDF+JG7o2wK0L7bOTS47VLG5rIEZ+dQQxi2IMnSieb"
  totpVaultKey: "wRxQDGzyWPzbox2LENyPjeutAzqHn/5hHXMbO8rTtz4="

  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - plausible.192.168.86.224.nip.io
    path: /
    tls:
      - secretName: plausible-tls-certificate
        hosts:
          - plausible.192.168.86.224.nip.io

  postgresql:
    enabled: true
    primary:
      persistence:
        enabled: true
        size: 10Gi
        storageClass: standard-rwo

  clickhouse:
    enabled: true
    persistence:
      enabled: true
      size: 20Gi
      storageClass: standard-rwo
