elementweb:
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/target: "homelab-tunnel.192.168.86.224.nip.io"
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    hosts:
      - host: &frontend_host chat.192.168.86.224.nip.io
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: element-tls-certificate
        hosts:
          - *frontend_host
  config:
    default:
      base_url: https://matrix.192.168.86.224.nip.io
      server_name: 192.168.86.224.nip.io

dendrite:
  dendrite_config:
    global:
      server_name: matrix.192.168.86.224.nip.io
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hostName: matrix.192.168.86.224.nip.io
    tls:
      - hosts:
          - matrix.192.168.86.224.nip.io
        secretName: matrix-tls-certificate
  postgresql:
    enabled: true
    image:
      repository: bitnamilegacy/postgresql
